name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Lua 5.1
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run all test files
        run: |
          find test -name '*.lua' -exec ./.lua/bin/lua5.1 {} \;
