name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Lua 5.1
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: ./run-tests.sh
